server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST}:8888
      name: api-gateway
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASS}
      profile: ${SPRING_PROFILES_ACTIVE:default}
      fail-fast: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.cloud.config: DEBUG
