server:
  port: 8078
  servlet:
    context-path: /api
spring:
  application:
    name: transaction-account-ms
  webflux:
    base-path: /api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST}:8888
      name: transaction-account-ms
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASS}
      profile: ${SPRING_PROFILES_ACTIVE:default}
      fail-fast: true
